services:
  json-server:
    build:
      dockerfile: Dockerfile.json-server
    image: ghcr.io/liszkai-dominik/joke-jsonserver:0.3

    ports:
      - "3000:80"

  front-end: 
    build:
      dockerfile: Dockerfile.front-end
    image: ghcr.io/liszkai-dominik/joke-frontend:0.3

    ports:
      - "8001:80"